package com.Housing2;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;

// TODO: Auto-generated Javadoc

/**
 * The Class Footer.
 */
public class Footer extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The main layout.
     */
    @AutoGenerated
    private HorizontalLayout mainLayout;

    /**
     * The link_4.
     */
    @AutoGenerated
    private Link link_4;

    /**
     * The label_1.
     */
    @AutoGenerated
    private Label label_1;

    /**
     * The link_3.
     */
    @AutoGenerated
    private Link link_3;

    /**
     * The link_2.
     */
    @AutoGenerated
    private Link link_2;

    /**
     * The link_1.
     */
    @AutoGenerated
    private Link link_1;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public Footer() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        mainLayout.setStyleName("footer");

        // TODO add user code here
    }

    /**
     * Builds the main layout.
     *
     * @return the horizontal layout
     */
    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);

        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);
//		mainLayout.setSizeFull();


        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("-1px");
        label_1.setHeight("-1px");
        label_1.setValue("© DHBW Karlsruhe");
        mainLayout.addComponent(label_1);

        // link_4
        link_4 = new Link();
        link_4.setCaption("DHBW Karlsruhe");
        link_4.setImmediate(false);
        link_4.setWidth("-1px");
        link_4.setHeight("15px");
        mainLayout.addComponent(link_4);


        // link_1
        link_1 = new Link();
        link_1.setCaption("Impressum");
        link_1.setImmediate(false);
        link_1.setWidth("-1px");
        link_1.setHeight("-1px");
        mainLayout.addComponent(link_1);

        // link_2
        link_2 = new Link();
        link_2.setCaption("AGBs");
        link_2.setImmediate(false);
        link_2.setWidth("-1px");
        link_2.setHeight("-1px");
        mainLayout.addComponent(link_2);

        // link_3
        link_3 = new Link();
        link_3.setCaption("Kontakt");
        link_3.setImmediate(false);
        link_3.setWidth("-1px");
        link_3.setHeight("-1px");
        mainLayout.addComponent(link_3);

        return mainLayout;
    }

}